stages:
  - update_test_branch
update_test_branch:
  stage: update_test_branch
  only:
    - testing # Trigger the pipeline only when the main branch is updated
  before_script:
    - apk update # Update package lists (optional, but recommended)
    - apk add git # Install Git
  script:
    - git config --global user.email $(git --no-pager show -s --format='%ae' HEAD)
    - git config --global user.name $(git --no-pager show -s --format='%an' HEAD)

    # Clone the repository
    - pwd
    - git clone https://oauth2:${ACCESS_TOKEN}@gitlab-ee.unimelb.edu.au/enterpriseapps/InfrastructureApps/eia-simgame/eia-simgame.git

    - cd eia-simgame
    # Create a temporary directory to extract the files from the main branch
    - mkdir /tmp/src
    - git checkout testing
    - cp -R * /tmp/src
    - git checkout test
    - rm -rf src
    - cp -R /tmp/src src


    # Add changes and commit
    - git add src/
    - git commit -m "Update test branch with changes from data-server branch"

    # Push the changes to the test branch
    - git push https://oauth2:${ACCESS_TOKEN}@gitlab-ee.unimelb.edu.au/enterpriseapps/InfrastructureApps/eia-simgame/eia-simgame.git dev
